// <auto-generated />
namespace SmartSpend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class uf3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uf3));
        
        string IMigrationMetadata.Id
        {
            get { return "202609201917211_uf3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
